package com.oracle.demo.model.server.serviceinterface;

import com.oracle.demo.model.AppModuleImpl;
import com.oracle.demo.model.common.DepartmentsViewSDO;
import com.oracle.demo.model.common.EmpDetailsSDO;
import com.oracle.demo.model.common.serviceinterface.AppModuleService;

import java.lang.reflect.Method;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.ejb.Remote;
import javax.ejb.Stateless;

import javax.interceptor.Interceptors;

import oracle.jbo.common.Diagnostic;
import oracle.jbo.common.sdo.SDOHelper;
import oracle.jbo.server.svc.ServiceContextInterceptor;
import oracle.jbo.server.svc.ServiceImpl;
import oracle.jbo.service.errors.ServiceException;

import oracle.webservices.annotations.PortableWebService;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 05 12:19:19 CST 2013
// ---------------------------------------------------------------------
@Stateless(name="com.oracle.demo.model.common.AppModuleServiceBean", mappedName="AppModuleServiceBean")
@Remote(AppModuleService.class)
@PortableWebService(targetNamespace="/com/oracle/demo/model/common/", serviceName="AppModuleService", portName="AppModuleServiceSoapHttpPort",
    endpointInterface="com.oracle.demo.model.common.serviceinterface.AppModuleService")
@Interceptors( { ServiceContextInterceptor.class })
public class AppModuleServiceImpl extends ServiceImpl implements AppModuleService {
    private static boolean _isInited = false;
    private static final Map _map = new HashMap();

    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleServiceImpl() {
        init();
        setApplicationModuleDefName("com.oracle.demo.model.AppModule");
        setConfigurationName("AppModuleService");
    }

    /**
     * Generated method. Do not modify. Do initialization in the constructor
     */
    protected void init() {
        if (_isInited) {
            return;
        }
        synchronized (AppModuleServiceImpl.class) {
            if (_isInited) {
                return;
            }
            try {
                SDOHelper.INSTANCE.defineSchema("com/oracle/demo/model/common/serviceinterface/", "AppModuleService.xsd");
                _map.put("getDepartments", AppModuleImpl.class.getMethod("getDepartments", new Class[] { }));
                _map.put("getEmployee", AppModuleImpl.class.getMethod("getEmployee", new Class[] { Integer.class }));
                _isInited = true;
            } catch (Exception ex) {
                Diagnostic.printStackTrace(ex);
            }
        }
    }

    /**
     * getDepartments: generated method. Do not modify.
     */
    public List<DepartmentsViewSDO> getDepartments() throws ServiceException {
        return (List<DepartmentsViewSDO>)invokeCustom((Method)_map.get("getDepartments"), new Object[] { },
                                                      new String[] { }, DepartmentsViewSDO.class, false);
    }

    /**
     * getEmployee: generated method. Do not modify.
     */
    public EmpDetailsSDO getEmployee(Integer empId) throws ServiceException {
        return (EmpDetailsSDO)invokeCustom((Method)_map.get("getEmployee"), new Object[] { empId },
                                           new String[] { null }, EmpDetailsSDO.class, false);
    }
}
