package com.oracle.demo.model;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 05 12:16:51 CST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmpDetailsImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public EmpDetailsImpl() {
    }
}
